version: "3.5"
services:
  postgres:
    build:
      context: ./
    image: postgres_image
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file: ./.env
    command: ["postgres", "-c", "log_statement=all"]
